language: node_js

node_js:
  - 12

script:
  - npm run blog:build
  - cd blog/.vuepress/dist
  - git clone https://github.com/creativeknot/creativeknot.github.io.git .gh-pages
  - rm -rf .gh-pages/assets
  - cp -rf * .gh-pages/
  - cd .gh-pages/
  - git remote add deploy https://$GH_TOKEN@github.com/creativeknot/creativeknot.github.io.git
  - git add -A && git commit -m "update - source at creativeknot/website"
  - git push deploy master
