language: node_js

branches:
  only:
    - main

node_js:
  - 14

script:
  - npm install
  - npm run build
  - git clone https://github.com/creativenull/creativenull.github.io.git .gh-pages
  - rm -rfv .gh-pages/assets
  - cp -rfv blog/.vuepress/dist/* ./.gh-pages
  - cd ./.gh-pages
  - git remote add deploy https://$GH_TOKEN@github.com/creativenull/creativenull.github.io.git
  - git add -A && git commit -m 'updated from creativenull/website'
  - git push deploy main
