language: node_js

node_js:
  - 10

script:
  - yarn blog:build
  - cd blog/.vuepress/dist
  - git clone https://github.com/creativenobu/creativenobu.github.io.git .gh-pages
  - rm -rf .gh-pages/assets
  - cp -rf * .gh-pages/
  - cd gh-pages/
  - git add -A && git commit -m "update website"
